import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import Nav from "../pages/index/nav";
import Main from "../pages/index/main";
import Aection from "../pages/index/aection";

const workProject = ["美甲", "保養", "腳底"];

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Good Daily Nails</title>
                <meta
                    name="description"
                    content="Generated by Good Daily Nails"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* index */}
            <Nav />
            <Main />
            <Aection />

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
