import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const workProject = ["美甲", "保養", "腳底"];

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Good Daily Nails</title>
                <meta
                    name="description"
                    content="Generated by Good Daily Nails"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className={(styles.navbarfixedtop, styles.container)}>
                <div className={styles.nav}>
                    {/* <h3 className={styles.nav}>女子的日常</h3> */}
                    <Link href="/" replace>
                        <a className={styles.nav}>女子の日常</a>
                    </Link>
                    <div className={styles.navbox}></div>
                    <div className={styles.navp}>
                        <ul className={styles.flex}>
                            <li>
                                <Link href="/" replace>
                                    <a>About</a>
                                </Link>
                            </li>
                            <li>
                                <Link href="/" replace>
                                    <a>Work</a>
                                </Link>
                            </li>
                            <li>
                                <Link href="/" replace>
                                    <a>Blog</a>
                                </Link>
                            </li>
                            <li>
                                <Link href="/" replace>
                                    <a>Contact</a>
                                </Link>
                            </li>
                        </ul>
                    </div>
                </div>
                <div className={styles.globalnavitemsns}>
                    <Link classNam={styles.nsicon} href="/" replace>
                        <a>
                            <Image
                                src="/images/facebook.png"
                                alt="facebook Logo"
                                width={32}
                                height={32}
                            />
                        </a>
                    </Link>
                    <Link classNam={styles.nsicon} href="/" replace>
                        <a>
                            <Image
                                src="/images/instagram.png"
                                alt="instagram Logo"
                                width={32}
                                height={32}
                            />
                        </a>
                    </Link>
                    <Link classNam={styles.nsicon} href="/" replace>
                        <a>
                            <Image
                                src="/images/line.png"
                                alt="line Logo"
                                width={36}
                                height={36}
                            />
                        </a>
                    </Link>
                </div>
            </nav>

            <main className={styles.main}>
                {/* 主 */}
                <div className={styles.flex}>
                    <h1 className={(styles.mainbox, styles.maintitle)}>
                        Good Daily Nails
                        <p style={{ fontSize: "23px" }}>Girl Nail Design</p>
                        <p style={{ fontSize: "23px" }}>
                            お客さまと共に課題に向き合い、
                            <br />
                            効果的なデザインをご提案いたします。
                        </p>
                    </h1>
                    <div>
                        <Image
                            src="/images/DSC_9610.jpg"
                            alt="Good Day Nails"
                            max-width={100}
                            width={540}
                            height={540}
                        />
                    </div>
                </div>

                {/* 關於我 */}
                <div
                    className={styles.flex}
                    style={{ margin: "3rem auto 2rem", padding: "3rem" }}
                >
                    <div>
                        <Image
                            src="/images/DSC_3087.jpg"
                            alt="Girl"
                            max-width={100}
                            width={440}
                            height={440}
                            objectFit="cover"
                        />
                    </div>
                    <div
                        style={{
                            margin: "3rem",
                            padding: "3rem",
                            backgroundColor: "#E8E8D0",
                        }}
                    >
                        <h1 style={{ width: "350px", textAlign: "left" }}>
                            About
                        </h1>
                        <p>私について</p>
                        <p>
                            ...............................................................................................
                        </p>
                        <p>
                            ...............................................................................................
                        </p>
                        <p>
                            ...............................................................................................
                        </p>
                        <div
                            style={{
                                textAlign: "right",
                                marginRight: "1.2rem",
                            }}
                        >
                            <Link href="/" replace>
                                <a>view more</a>
                            </Link>
                        </div>
                        <div
                            style={{ textAlign: "right", marginTop: "-0.5rem" }}
                        >
                            <Image
                                src="/images/arrow.png"
                                alt="arrow"
                                max-width={100}
                                width={100}
                                height={5}
                            />
                        </div>
                    </div>
                </div>
                

                <div className={styles.grid}>
                    {/* <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>
                            Find in-depth information about Next.js features and
                            API.
                        </p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>
                            Learn about Next.js in an interactive course with
                            quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>
                            Discover and deploy boilerplate example Next.js
                            projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL
                            with Vercel.
                        </p>
                    </a> */}
                </div>
            </main>

            {/* 工作 */}
            <section className={styles.back}>
            <h1 style={{textAlign:'center',margin:'2rem',padding:'2rem'}}>Work</h1>
                <div
                    style={{
                        width: "960px",
                        height:"560px",
                        margin: "0 auto",
                        padding: "0",
                    }}
                    // 更改背景框度
                >
                    
                    <div className={styles.Home_card___LpL1}>
                        <Image
                            className={styles.Home_card___LpL1Image}
                            src="/images/DSC_9610.jpg"
                            alt=""
                            width={360}
                            height={223}
                        />
                        <div className={styles.info}>
                            <div style={{ marginTop: "60px" }}>
                                <p>Hello World!</p>
                            </div>
                        </div>
                    </div>

                    <div className={styles.Home_card___LpL1}>
                        <Image
                            src="/images/DSC_9610.jpg"
                            alt=""
                            width={360}
                            height={223}
                        />
                        <div className={styles.info}>
                            <div style={{ marginTop: "60px" }}>
                                <p>Hello World!</p>
                            </div>
                        </div>
                    </div>

                    <div className={(styles.flex, styles.Home_card___LpL1)}>
                        <Image
                            src="/images/DSC_9610.jpg"
                            alt=""
                            width={360}
                            height={223}
                        />
                        <div className={styles.info}>
                            <div style={{ marginTop: "60px" }}>
                                <p>Hello World!</p>
                            </div>
                        </div>
                    </div>
                </div>
                <p style={{ textAlign: "center", margin: "0 auto" }}>
                    view more
                </p>
            </section>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
